FROM node:16.15.0-bullseye-slim as build

#for avoid python print buffering
ENV PYTHONUNBUFFERED=1

COPY src/WebApp/reddit-stock-dashboard /home/reddit-stock-dashboard

WORKDIR /home/reddit-stock-dashboard
RUN npm install
RUN npm run build
#RUN ls
#COPY ./build /home/reddit-stock-dashboard/build

FROM nginx:1.20.2

COPY --from=build /home/reddit-stock-dashboard/build/ /usr/share/nginx/html
