apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: react-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-deploy
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scraper-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scraper-deploy
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 800
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-deploy
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30