apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-scraper
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-scraper-azure
            image: nrregistry.azurecr.io/daily-scraper
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          concurrencyPolicy: Forbid
          successfulJobsHistoryLimit: 100