apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deploy
  labels:
    app: scraper-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-test
  template:
    metadata:
      labels:
        app: scraper-test
    spec:
      containers:
      - name: scraper-azure
        #image: nrregistry.azurecr.io/client-test:2.3
        image: nrregistry.azurecr.io/scrapers-test
        #tty: true
        #stdin: true
        #se non ci metto un comando tipo questo non crea il container (va tipo in loop)
        #command: ["/bin/sleep", "3650d"]
        env:
          - name: KEY_VAULT_NAME
            value: redditKeys
          - name: AZURE_TENANT_ID
            value: e99647dc-1b08-454a-bf8c-699181b389ab
          - name: AZURE_CLIENT_SECRET
            value: tPt8wiHYFt9k-ljI-QhLJsPInTPvWYsA8A
          - name: AZURE_CLIENT_ID
            value: 1e20a665-6170-4f7e-86c2-ed8f8c1429d6
          
      #imagePullSecrets:
      #  - name: regcred
