apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
  labels:
    app: client-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-test
  template:
    metadata:
      labels:
        app: client-test
    spec:
      containers:
      - name: client-test-azure
        #image: nrregistry.azurecr.io/client-test:2.3
        image: nrregistry.azurecr.io/client-k8s
        #tty: true
        #stdin: true
        #se non ci metto un comando tipo questo non crea il container (va tipo in loop)
        #command: ["/bin/sleep", "3650d"]
        env:
          - name: SERVER_NAME
            value: server-test-svc
      #imagePullSecrets:
      #  - name: regcred
